---
# tasks file for oc_exec
- name: Run shell command in a pod
  vars:
    shell_command: "oc exec -i {{ oc_exec_pod }} -- /bin/bash -c '{{ oc_exec_pod_command }}'"
  ansible.builtin.shell: "{{ shell_command }}"
  args:
    executable: "{{ exec_shell }}"
    chdir: "{{ work_dir }}"
  become: "{{ become }}"
  become_user: "{{ target_user }}"
  become_flags: "{{ become_flags }}"
  register: oc_exec_result
  failed_when: >
    (p_failed_when is defined and oc_exec_result == p_failed_when) or
    (p_failed_when is not defined and oc_exec_result.rc != 0)
